export const SET_CLIENTS_DATA = 'SET_CLIENTS_DATA';
export const GET_CLIENTS_DATA = 'GET_CLIENTS_DATA';
export const SHOW_APP_ERROR = 'SHOW_APP_MESSAGE';
export const HIDE_APP_ERROR = 'HIDE_APP_MESSAGE';
export const SET_LOADING = 'SET_LOADING';
export const SET_NEW_CLIENT_DATA = 'SET_NEW_CLIENT_DATA';
